### ISSUE TITLE
Cannot login and create account due to "Something went wrong" error

### ISSUE THREAD

**Issue by eikibw** [aws/studio-lab-examples#254]
Help, I can't login into sagemaker.
My account is verified, and I have already used it several times before, but I can't log in today.
![Screenshot 2024-04-02 132513](https://github.com/aws/studio-lab-examples/assets/117745256/06dad21e-61b3-463d-b3ac-d9807f7b4eca)

**Comment by Vendetta-S** [comment]
This has happened so randomly, and yet it gets fixed if you wait for a few minutes
only problem, it wastes your runtime equals to the amount of minutes you wait which is really annoying

does anyone know this is a server issue?

**Comment by MicheleMonclova** [comment]
Thanks for the comments.  I honestly do not know how to reproduce with the info given but please keep in mind that the user name is case sensitive.
Vendetta-S - I am not sure how this would waste your runtime.  You need to log in before you start a runtime. can you please explain further?

**Comment by eikibw** [comment]
it's fixed for me now. After a week, I restarted my router and somehow I can login now.

**Comment by Vendetta-S** [comment]
> Vendetta-S - I am not sure how this would waste your runtime. You need to log in before you start a runtime. can you please explain further?

Essentially, when running a runtime there is this error on the site that says the same thing as the one here, and I can't really leave it alone as it'll close my connection to the server
as soon as I refresh the page, I couldn't login and even when I try to delete the cookies it still didn't work, and waiting actually wasted the runtime

**Comment by CALEB789** [comment]
it is caused by the cors origin policy in chrome
![Capture](https://github.com/aws/studio-lab-examples/assets/58883113/5e98050d-33f5-4cd3-ab9e-959621f6b8e2)
to disable it for a short time you need to run this
Open Start window
Search Run and open it or press Window+ R
Paste chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security and execute it
This will open a new browser with web security disabled.
You can now access your project in this browser without worrying about the CORS errors.

**Comment by Vendetta-S** [comment]
> it is caused by the cors origin policy in chrome ![Capture](https://private-user-images.githubusercontent.com/58883113/322187567-5e98050d-33f5-4cd3-ab9e-959621f6b8e2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODQ5NjYsIm5iZiI6MTcxMzA4NDY2NiwicGF0aCI6Ii81ODg4MzExMy8zMjIxODc1NjctNWU5ODA1MGQtMzNmNS00Y2QzLWFiOWUtOTU5NjIxZjZiOGUyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA4NTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYTAyYjRlZjI2NGU5OTJlYjEzZDY4MjlmMjY0MTdkMzFlZDY5NWEwOTg1NjMzMDdhNjNiNGM2NGE1MTQxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNxGgE1f--B9DsVqR7lqrwRJftiJhMAaCGrNRXYJ67o) to disable it for a short time you need to run this Open Start window Search Run and open it or press Window+ R Paste chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security and execute it This will open a new browser with web security disabled. You can now access your project in this browser without worrying about the CORS errors. but it is a problem with **aws sageMaker Studio Lab**

tested this and it works, but it is pretty annoying how it's hasn't been fixed yet

**Comment by MicheleMonclova** [comment]
Thanks Vendetta-S for this information. We will look into this.

**Comment by Vendetta-S** [comment]
Update, just realized, I can never login the same without using the fix that Caleb suggested, as it kept staying like the above issue's screenshot. I am using chrome so it won't probably matter but most people use them.

**Comment by icoxfog417** [comment]
I confirmed this error occurs not only Chrome but also Edge of the other browsers. Let us investigate to deliver the solution quickly.

**Comment by CALEB789** [comment]
Basically that has to be the issue on every browser..... May be one of
their scripts or all  is not on the same origin. That can cause the corse
origin policy errors

**Comment by CALEB789** [comment]
May be this Stack  Overflow post might be of some help
https://stackoverflow.com/questions/22343384/the-access-control-allow-origin-header-contains-multiple-values

**Comment by icoxfog417** [comment]
We continue to find out root cause of this issue and taking action rapidly. We will announce the progress in this issue.

**Comment by icoxfog417** [comment]
After our survery, we found "**try login / create new account several times (around 5 times)**" is temporary solution, 87.5% of users can login/create new account after several trials.  Of course, we try to solve the root cause and will report to community if the problem totally solved.

**Comment by Vendetta-S** [comment]
Oh and to anyone wanting to just not needing to run the program all over, you'll have to create a new profile in the settings, without email, just the name. Then going to chrome://settings/manageProfile, and activate create shortcut on desktop. Then, all you need to do is exit, locate it and click properties, "Target" field is where you need to remove and copy paste this: "C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 4" --user-data-dir="C://Chrome dev session" --disable-web-security"

**Comment by Vendetta-S** [comment]
The profile being your own profile, for instance Profile 2 or 4 etc

**Comment by speraltado** [comment]
This is where the error comes from on my end.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gateway.prod.us-east-2.studiolab.sagemaker.aws/v1/signin. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://studiolab.sagemaker.aws, *’).

**Comment by icoxfog417** [comment]
We have deployed a solution. We expect all users to be able to log in or create new accounts without any issues. If you encounter any problems, please don't hesitate to reach out to us!

**Comment by Vendetta-S** [comment]
Holy it's been fixed! Thank you!
Now I just need to monitor just in case something goes wrong again...

**Comment by ahmadfalcon** [comment]
@icoxfog417 I got approval of signing up but facing same issue from many days

**Comment by MicheleMonclova** [comment]
@ahmadfalcon, you are still getting the same error? "Something went wrong. Please try again later"?
What happens if you try again?

**Comment by MicheleMonclova** [comment]
This issue should be resolved. please let me know if anyone is still hitting it else we will close.

**Comment by TheYoungBaller** [comment]
> it is caused by the cors origin policy in chrome ![Capture](https://private-user-images.githubusercontent.com/58883113/322187567-5e98050d-33f5-4cd3-ab9e-959621f6b8e2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjIwNDMsIm5iZiI6MTcxNTM2MTc0MywicGF0aCI6Ii81ODg4MzExMy8zMjIxODc1NjctNWU5ODA1MGQtMzNmNS00Y2QzLWFiOWUtOTU5NjIxZjZiOGUyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE3MjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzllMGYwZTE3YjM3YjJjN2NkMWE0ZDRmYzJjMjE3ODRjN2UwOGFlZWJjYjg2NmI4MGZhM2NmM2JkMjgwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.twMJUJhgsfTJ95-QsQVBp2AjP24tungyH86pd6tmf8c) to disable it for a short time you need to run this Open Start window Search Run and open it or press Window+ R Paste chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security and execute it This will open a new browser with web security disabled. You can now access your project in this browser without worrying about the CORS errors. but it is a problem with **aws sageMaker Studio Lab**

But after trying this solution it says my email is not allowed, i even tried with 3 different email and the results still the same

**Comment by TheYoungBaller** [comment]
> We have deployed a solution. We expect all users to be able to log in or create new accounts without any issues. If you encounter any problems, please don't hesitate to reach out to us!

umm i think i got the same problem, when i try to signing in it gives me endless captchas then when i try to request a new account, the same "something went wrong" error got me.

**Comment by CALEB789** [comment]
> > it is caused by the cors origin policy in chrome ![Capture](https://private-user-images.githubusercontent.com/58883113/322187567-5e98050d-33f5-4cd3-ab9e-959621f6b8e2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjIwNDMsIm5iZiI6MTcxNTM2MTc0MywicGF0aCI6Ii81ODg4MzExMy8zMjIxODc1NjctNWU5ODA1MGQtMzNmNS00Y2QzLWFiOWUtOTU5NjIxZjZiOGUyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE3MjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzllMGYwZTE3YjM3YjJjN2NkMWE0ZDRmYzJjMjE3ODRjN2UwOGFlZWJjYjg2NmI4MGZhM2NmM2JkMjgwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.twMJUJhgsfTJ95-QsQVBp2AjP24tungyH86pd6tmf8c) to disable it for a short time you need to run this Open Start window Search Run and open it or press Window+ R Paste chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security and execute it This will open a new browser with web security disabled. You can now access your project in this browser without worrying about the CORS errors. but it is a problem with **aws sageMaker Studio Lab**
> 
> But after trying this solution it says my email is not allowed, i even tried with 3 different email and the results still the same

Hello. I think Personal Email Address are not allowed.

You have to use a business email address for example xfji@gb.com

**Comment by TheYoungBaller** [comment]
Thanks for the reply, but unfortunately i tried my two organization email and both of them ended up the same

**Comment by CALEB789** [comment]
So can you try to press CRTL + SHIFT + I TO OPEN THE DEV TOOLS. AND THEN YOU GO TO THE CONSOLE TAB. AND THEN POST A SCREEN SHOT HERE

**Comment by TheYoungBaller** [comment]
![image](https://github.com/aws/studio-lab-examples/assets/168959817/53f103f9-bdda-4d05-a547-6d549248a470)

**Comment by TheYoungBaller** [comment]
![image](https://github.com/aws/studio-lab-examples/assets/168959817/fde88710-e4b8-49e7-9c88-274b441d274c)
-The disabled security version

![image](https://github.com/aws/studio-lab-examples/assets/168959817/acfdba33-c4c0-4937-b904-f5147ad4dbca)
-The normal version

**Comment by CALEB789** [comment]
So it is not a problem with the cors origin policy.

The contributers will look at it. It appears it is some internal thing

**Comment by TheYoungBaller** [comment]
alright then thanks, ill wait

**Comment by Vendetta-S** [comment]
Cannot believe this has happened to me, I tried to delete and re-add my sagemaker studio lab account but no responses at all (usually I get the email right away)
Great
